### ISSUE TITLE
Just raising a question about scalability

### ISSUE THREAD

**Issue by vongohren** [mikaelvesavuori/cloud-run-ts-apollo-graphql#1]
Have you made any thoughts on how much this cloudrun instance can withstand? Or in what scenario this is a doable approach? I know it scales by itself, but how much are we maybe looking at :D ?

**Comment by mikaelvesavuori** [comment]
Hey! Sorry for the late reply.

The short answer is that I haven't (myself) pressure-tested Cloud Run for any massive services. At my company we've done a few projects on GCP, mostly Cloud Functions, without a hitch.

I've been working exclusively with various clients for the last 3 years and running their systems on (several) serverless platforms. Right now I am a Platform/Operational Architect in an enterprise with a few hundred developers and about 25 different teams, all using only AWS serverless tech. Scaling has never been an issue, on the contrary, this is one of the aspects that works flawlessly.

There's a good set of articles (starting with [https://blog.tomilkieway.com/72k-1/](https://blog.tomilkieway.com/72k-1/)) about how the scaling of Cloud Run actually works so well, you could go bankrupt long before you get technical issues. Hint: The entire application these guys made is a colossal failure of thinking right about the architecture; I'm using it more to prove the point about scaling.

Is that good as an answer?

**Comment by mikaelvesavuori** [comment]
Quick addendum: From an architectural standpoint you would still of course want to distribute API responsibilities to more than a single endpoint, for several reasons. Scaling of individual nodes/services becomes less of an issue when overall load is distributed across a wider set of (sub-)services.

**Comment by vongohren** [comment]
@mikaelvesavuori thanks for the response all together! It is a very qualified answer in my view!
I have gotte much more insight, and it is comforting to hear your experience on this.

Your last addendum is important and thanks for adding it!

I will close this now
